apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-worker
  labels:
    app: queue-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: queue-worker
  template:
    metadata:
      labels:
        app: queue-worker
        env: production-us
        team: platform
        tier: data
    spec:
      containers:
      - name: api
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/production-us/nginx:1.25.0
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
  priorityClassName: critical
