apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-pool
  labels:
    app: worker-pool
spec:
  replicas: 6
  selector:
    matchLabels:
      app: worker-pool
  template:
    metadata:
      labels:
        app: worker-pool
        team: frontend
        tier: backend
        env: production-us
    spec:
      containers:
      - name: web
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/production-us/node:1.25.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
  priorityClassName: critical
